project:
  type: default
  title: "Forensic Neuropsych Report"
  execute-dir: project
  render:
    - "!quarto/"
    - template.qmd

format:
  neurotyp-forensic-typst:
    keep-typ: true
    keep-md: true
    papersize: "a4"
    bodyfont: "Equity B OTF"
    sansfont: "Work Sans"
    fontsize: 12pt
    number-sections: false
    number-offset: 1
    shift-heading-level-by: 0
    citeproc: true
    csl: inst/resources/bib/apa.csl
    fig-width: 6
    fig-height: 4
    fig-format: svg

execute:
  warning: false
  echo: false
  message: false
  freeze: auto
  cache: true
  engine: knitr
  tools:
    r: "/usr/local/bin/R"

editor:
  markdown:
    wrap: sentence
    canonical: true
fig-width: 6
fig-asp: 0.618
out-width: 70%
fig-align: center
fig-format: svg
fig-dpi: 270
df-print: kable
reference-location: document
bibliography: inst/resources/bib/refs.bib
