project:
  type: default
  execute-dir: file
  render:
    - Biggie.qmd

format:
  neurotyp-pediatric-typst:
    keep-typ: true
    keep-md: true
    papersize: us-letter
    bodyfont: "ScholaX"
    sansfont: "ScholaX"
    fontsize: 12pt
    number-sections: false
    citeproc: false
    csl: /bib/apa

execute:
  warning: false
  echo: false
  message: false
  freeze: auto
  cache: true

editor:
  markdown:
    wrap: sentence
    canonical: true
fig-width: 6
fig-asp: 0.618
out-width: "70%"
fig-align: center
fig-format: svg
fig-dpi: 270
df-print: kable
reference-location: document
bibliography: /bib/refs.bib
